# Generated by Django 3.2.3 on 2021-05-14 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('obj', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductivityPerHour',
            fields=[
                ('chain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DashboardMonitoring.chain')),
                ('hour', models.IntegerField()),
                ('productivity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ref', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardMonitoring.chain')),
            ],
        ),
    ]
