# Generated by Django 3.2.3 on 2021-05-14 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardMonitoring', '0005_auto_20210514_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productivityperhour',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DashboardMonitoring.chain'),
        ),
    ]
