# Generated by Django 3.2.3 on 2021-05-14 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardMonitoring', '0007_auto_20210514_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='productivityperhour',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DashboardMonitoring.product'),
        ),
        migrations.AddField(
            model_name='productivityperhour',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
