# Generated by Django 3.2.3 on 2021-05-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardMonitoring', '0008_auto_20210514_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productivityperhour',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
