# Generated by Django 3.2.3 on 2021-05-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardMonitoring', '0009_alter_productivityperhour_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productivityperhour',
            name='product',
        ),
        migrations.AddField(
            model_name='productivityperhour',
            name='product',
            field=models.ManyToManyField(null=True, to='DashboardMonitoring.Product'),
        ),
    ]
