# Generated by Django 3.2.3 on 2021-05-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardMonitoring', '0010_auto_20210514_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productivityperhour',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
