# Generated by Django 3.2.3 on 2021-05-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardMonitoring', '0011_auto_20210514_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productivityperhour',
            name='chain',
        ),
        migrations.AddField(
            model_name='productivityperhour',
            name='chain',
            field=models.ManyToManyField(to='DashboardMonitoring.Chain'),
        ),
    ]
