# Generated by Django 3.2.3 on 2021-05-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardMonitoring', '0014_auto_20210515_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productivityperhour',
            name='hourRef',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
