# Generated by Django 3.2.3 on 2021-05-15 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardMonitoring', '0017_alter_productivityperhour_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='productivityperhour',
            name='id',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productivityperhour',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardMonitoring.chain'),
        ),
    ]
