# Generated by Django 3.2.3 on 2021-05-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardMonitoring', '0021_alter_productivityperhour_hour'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productivityperhour',
            unique_together={('chain', 'hour')},
        ),
    ]
