# Generated by Django 3.2.3 on 2021-05-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardMonitoring', '0025_alter_productivityperhour_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='productivityperhour',
            name='retouch',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
