# Generated by Django 3.2.3 on 2021-05-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardMonitoring', '0026_productivityperhour_retouch'),
    ]

    operations = [
        migrations.AddField(
            model_name='productivityperhour',
            name='latest_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
