# Generated by Django 3.2.3 on 2021-05-15 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardMonitoring', '0027_productivityperhour_latest_modification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productivityperhour',
            name='latest_modification',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
